// A LOT OF THE GENERATION CODE HAS BEEN STOLEN AND TRANSLATED FROM https://github.com/openai/dallify-discord-bot

const { SlashCommandBuilder, AttachmentBuilder } = require('discord.js');

module.exports = {
	data: new SlashCommandBuilder()
		.setName('paint')
		.setDescription('Uses openAI\'s DALLE to imagine anything you want')
        .addStringOption(option =>
            option
                .setName('prompt')
                .setRequired(true)
                .setDescription('The prompt you want to generate an image based off of')),
        // .addIntegerOption(option => 
        //   option
        //     .setName('amount')
        //     .setRequired(true)
        //     .setDescription('The number of images to generate')
        //     .min_value(1)
        //     .maxValue(4)),
	async execute(interaction) {
    const uuid = interaction.user.id;
    const prompt = interaction.options.getString("prompt");
    const count = 1 //interaction.options.getInteger("amount");

    if (prompt == null) {
      await interaction.reply("Prompt must exist.");
    }

    await interaction.deferReply(); // tell discord we have acknowledged but need some time to finish this reply

    // get openai object
    const { openai } = require('..'); // this has to stay inside the execute because outside of the module export it appears as an export to the deploy command script
    
    try{
      const completion = await openai.createImage({
        prompt: prompt,
        n: count,
        size: "1024x1024",
      });
      
      image_url = completion.data.data[0].url;
      
      const attachment = new AttachmentBuilder(image_url, { name: 'painting.png' })
      await interaction.followUp({content:`**Prompt:** ${prompt}\n**Generated by:** <@${uuid}>\n`,files:[attachment]});
    }
    catch (e) {
      interaction.followUp("Something went wrong!").catch(console.error);
      console.log(e)
    } 
	},
};